Repository fluxninja/aperture-java, pull requests merged in 2022-10, with the labels that each got.

#15 Actions native Concurrency instead of Consecutiveness
  .github/workflows/issues-notion-sync.yml
Labels: size/S

#12 Prepare for releasing to Maven Central
  .circleci/config.yml
  .circleci/continue-workflows.yml
  .gitignore
  build.gradle
  build.gradle.kts
  gradle/wrapper/gradle-wrapper.jar
  settings.gradle
  settings.gradle.kts
  version.gradle.kts
Labels: size/L

#16 Release by tag tooling
  .circleci/continue-workflows.yml
  README.md
Labels: size/S

#17 Fix releases
  .circleci/config.yml
  .circleci/continue-workflows.yml
Labels: size/M

#14 WIP Implement Java SDK to send traces and create an example app
  build.gradle.kts
  src/main/java/com/fluxninja/aperture/example/App.java
  src/main/java/com/fluxninja/aperture/sdk/ApertureSDK.java
  src/main/java/com/fluxninja/aperture/sdk/ApertureSDKBuilder.java
  src/main/java/com/fluxninja/aperture/sdk/ApertureSDKException.java
  src/main/java/com/fluxninja/aperture/sdk/Constants.java
  src/main/java/com/fluxninja/aperture/sdk/Flow.java
  src/main/java/com/fluxninja/aperture/sdk/Utils.java
Labels: size/L

#18 Remove Java 8 build from CI
  .circleci/continue-workflows.yml
Labels: size/XS

#19 Remove clientIP constant
  src/main/java/com/fluxninja/aperture/sdk/Constants.java
Labels: size/XS

#23 Add dockerfile and example app configuration
  Dockerfile
  src/main/java/com/fluxninja/aperture/example/App.java
Labels: size/M

#24 Fix example app
  Dockerfile
  src/main/java/com/fluxninja/aperture/example/App.java
Labels: size/S

#26 Fix javadoc and sources publishing
  build.gradle.kts
  version.gradle.kts
Labels: size/XS

#28 Provide short decorator javadoc descriptions
  src/main/java/com/fluxninja/aperture/armeria/ApertureHTTPClient.java
  src/main/java/com/fluxninja/aperture/armeria/ApertureHTTPClientBuilder.java
  src/main/java/com/fluxninja/aperture/armeria/ApertureHTTPService.java
  src/main/java/com/fluxninja/aperture/armeria/ApertureHTTPServiceBuilder.java
  src/main/java/com/fluxninja/aperture/armeria/ApertureRPCClient.java
  src/main/java/com/fluxninja/aperture/armeria/ApertureRPCClientBuilder.java
  src/main/java/com/fluxninja/aperture/armeria/ApertureRPCService.java
  src/main/java/com/fluxninja/aperture/armeria/ApertureRPCServiceBuilder.java
Labels: size/S

#31 Bump snapshot version to 0.3.0
  version.gradle.kts
Labels: size/XS

#32 Add compatibility for java8
  .circleci/continue-workflows.yml
  src/main/java/com/fluxninja/aperture/armeria/HttpUtils.java
  src/main/java/com/fluxninja/aperture/example/ArmeriaClient.java
  src/main/java/com/fluxninja/aperture/example/ArmeriaServer.java
  src/main/java/com/fluxninja/aperture/sdk/ApertureSDK.java
Labels: size/S
