Repository fluxninja/aperture-java, pull requests merged in 2022-09, with the labels that each got.

#2 Set up GitHub Action to sync Issues to Notion
  .github/workflows/issues-notion-sync.yml
Labels: size/S

#3 Move github notion sync branch to fluxninja
  .github/workflows/issues-notion-sync.yml
Labels: size/XS

#4 Project scaffold setup
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/fluxninja/aperture/flowcontrol/v1/CheckRequest.java
  src/main/java/com/fluxninja/aperture/flowcontrol/v1/CheckRequestOrBuilder.java
  src/main/java/com/fluxninja/aperture/flowcontrol/v1/CheckResponse.java
  src/main/java/com/fluxninja/aperture/flowcontrol/v1/CheckResponseOrBuilder.java
  src/main/java/com/fluxninja/aperture/flowcontrol/v1/ClassifierInfo.java
  src/main/java/com/fluxninja/aperture/flowcontrol/v1/ClassifierInfoOrBuilder.java
  src/main/java/com/fluxninja/aperture/flowcontrol/v1/ControlPointInfo.java
  src/main/java/com/fluxninja/aperture/flowcontrol/v1/ControlPointInfoOrBuilder.java
  src/main/java/com/fluxninja/aperture/flowcontrol/v1/FlowControlServiceGrpc.java
  src/main/java/com/fluxninja/aperture/flowcontrol/v1/FlowcontrolProto.java
  src/main/java/com/fluxninja/aperture/flowcontrol/v1/FluxMeterInfo.java
  src/main/java/com/fluxninja/aperture/flowcontrol/v1/FluxMeterInfoOrBuilder.java
  src/main/java/com/fluxninja/aperture/flowcontrol/v1/LimiterDecision.java
  src/main/java/com/fluxninja/aperture/flowcontrol/v1/LimiterDecisionOrBuilder.java
  src/main/java/com/fluxninja/aperture/sdk/ApertureSDK.java
  src/main/java/com/fluxninja/aperture/sdk/ApertureSDKBuilder.java
  src/main/java/com/fluxninja/aperture/sdk/Constants.java
  src/main/java/com/fluxninja/aperture/sdk/Flow.java
  src/main/java/com/fluxninja/aperture/sdk/FlowStatus.java
Labels: size/XXL

#8 Add CI
  .circleci/config.yml
  .circleci/continue-workflows.yml
  .gitignore
  .pre-commit-config.yaml
  README.md
  build.gradle
  settings.gradle
  src/main/java/com/fluxninja/aperture/sdk/Constants.java
  src/main/java/com/fluxninja/aperture/sdk/Flow.java
Labels: size/L

#10 Update README.md
  README.md
Labels: size/S

#11 Add more JDK versions to CI
  .circleci/continue-workflows.yml
Labels: size/S

#13 Create LICENSE.txt
  LICENSE.txt
Labels: size/L
